version: '3'

services:
    shop-app:
        container_name: shop-node-mongo
        restart: always
        build: .
        ports:
            - '3000:3000'
        environment:
            - MONGODB_URI=${MONGODB_CONTAINER_URI}
        external_links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
